name: Test Server and Client

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: --quiet
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "22.x"

      - run: npm install

      - run: npm --prefix server install
      - run: npm --prefix client install

      - run: npm run test:server
        env:
          MONGODB: mongodb://localhost:27017/testdb

      - run: npm run test:client
